remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Aikata
logo: /assets/img/Aikata.jpg
description: |
  PhD Candidate at TU Graz
  <div class="profile-icons">
    <a href="https://dblp.org/pid/282/9289.html" aria-label="DBLP">
      <img src="/assets/img/dblp.svg" alt="DBLP">
    </a>
    <a href="https://scholar.google.com/citations?user=Z0onVEEAAAAJ&hl=en" aria-label="Google Scholar">
      <img src="/assets/img/googlescholar.svg" alt="Google Scholar">
    </a>
    <a href="https://github.com/aikata10" aria-label="GitHub">
      <img src="/assets/img/github.svg" alt="GitHub">
    </a>
    <a href="https://www.linkedin.com/in/aikata-12163b136/?originalSubdomain=at" aria-label="LinkedIn">
      <img src="/assets/img/linkedin.svg" alt="LinkedIn">
    </a>
  </div>
  <div class="header-link"><a href="/patents_publications.html"><strong>Patents &amp; Publications</strong></a></div>
  <div class="header-link"><a href="/Supervision.html"><strong>BSc &amp; MSc Project/Thesis Supervision</strong></a></div>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
